# Generated by Django 4.2.2 on 2023-07-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingtool",
            name="description",
            field=models.TextField(),
        ),
    ]
